from pathlib import Path

from yuxi import config

VIRTUAL_PATH_PREFIX = config.sandbox_virtual_path_prefix
WORKSPACE_DIR_NAME = "workspace"
WORKSPACE_AGENTS_DIR_NAME = "agents"
WORKSPACE_AGENTS_PROMPT_FILE_NAME = "AGENTS.md"
WORKSPACE_MEMORY_DIR_NAME = "memory"
WORKSPACE_MEMORY_FILE_NAME = "MEMORY.md"
UPLOADS_DIR_NAME = "uploads"
OUTPUTS_DIR_NAME = "outputs"
LARGE_TOOL_RESULTS_DIR_NAME = "large_tool_results"
CONVERSATION_HISTORY_DIR_NAME = "conversation_history"
VIRTUAL_SKILLS_PATH = "/home/gem/skills"

VIRTUAL_PATH_WORKSPACE = (Path(VIRTUAL_PATH_PREFIX) / WORKSPACE_DIR_NAME).as_posix()
VIRTUAL_PATH_MEMORY_FILE = (
    Path(VIRTUAL_PATH_WORKSPACE) / WORKSPACE_MEMORY_DIR_NAME / WORKSPACE_MEMORY_FILE_NAME
).as_posix()
VIRTUAL_PATH_UPLOADS = (Path(VIRTUAL_PATH_PREFIX) / UPLOADS_DIR_NAME).as_posix()
VIRTUAL_PATH_OUTPUTS = (Path(VIRTUAL_PATH_PREFIX) / OUTPUTS_DIR_NAME).as_posix()
VIRTUAL_PATH_LARGE_TOOL_RESULTS = (Path(VIRTUAL_PATH_OUTPUTS) / LARGE_TOOL_RESULTS_DIR_NAME).as_posix()
VIRTUAL_PATH_CONVERSATION_HISTORY = (Path(VIRTUAL_PATH_OUTPUTS) / CONVERSATION_HISTORY_DIR_NAME).as_posix()

__all__ = [
    "VIRTUAL_PATH_PREFIX",
    "WORKSPACE_DIR_NAME",
    "WORKSPACE_AGENTS_DIR_NAME",
    "WORKSPACE_AGENTS_PROMPT_FILE_NAME",
    "WORKSPACE_MEMORY_DIR_NAME",
    "WORKSPACE_MEMORY_FILE_NAME",
    "UPLOADS_DIR_NAME",
    "OUTPUTS_DIR_NAME",
    "LARGE_TOOL_RESULTS_DIR_NAME",
    "CONVERSATION_HISTORY_DIR_NAME",
    "VIRTUAL_PATH_WORKSPACE",
    "VIRTUAL_PATH_MEMORY_FILE",
    "VIRTUAL_PATH_UPLOADS",
    "VIRTUAL_PATH_OUTPUTS",
    "VIRTUAL_PATH_LARGE_TOOL_RESULTS",
    "VIRTUAL_PATH_CONVERSATION_HISTORY",
    "VIRTUAL_SKILLS_PATH",
]
